In [1]:
import gbs_functions as gbs
import gbs_functions_MN as old
from sympy import Matrix

In [2]:
display(gbs.moment([1,1,1]))
display(old.moment([1,1,1], displacement=False))

A[1, 2]*A[3, 4]*A[5, 6] + A[1, 2]*A[3, 5]*A[4, 6] + A[1, 2]*A[3, 6]*A[4, 5] + A[1, 3]*A[2, 4]*A[5, 6] + A[1, 3]*A[2, 5]*A[4, 6] + A[1, 3]*A[2, 6]*A[4, 5] + A[1, 4]*A[2, 3]*A[5, 6] + A[1, 4]*A[2, 5]*A[3, 6] + A[1, 4]*A[2, 6]*A[3, 5] + A[1, 5]*A[2, 3]*A[4, 6] + A[1, 5]*A[2, 4]*A[3, 6] + A[1, 5]*A[2, 6]*A[3, 4] + A[1, 6]*A[2, 3]*A[4, 5] + A[1, 6]*A[2, 4]*A[3, 5] + A[1, 6]*A[2, 5]*A[3, 4]

conjugate(M[1, 2])*conjugate(N[1, 3])*M[2, 3] + conjugate(M[1, 2])*conjugate(N[2, 3])*M[1, 3] + conjugate(M[1, 2])*M[1, 2]*N[3, 3] + conjugate(M[1, 3])*conjugate(N[1, 2])*M[2, 3] + conjugate(M[1, 3])*M[1, 2]*N[2, 3] + conjugate(M[1, 3])*M[1, 3]*N[2, 2] + conjugate(M[2, 3])*M[1, 2]*N[1, 3] + conjugate(M[2, 3])*M[1, 3]*N[1, 2] + conjugate(M[2, 3])*M[2, 3]*N[1, 1] + conjugate(N[1, 2])*conjugate(N[2, 3])*N[1, 3] + conjugate(N[1, 2])*N[1, 2]*N[3, 3] + conjugate(N[1, 3])*N[1, 2]*N[2, 3] + conjugate(N[1, 3])*N[1, 3]*N[2, 2] + conjugate(N[2, 3])*N[1, 1]*N[2, 3] + N[1, 1]*N[2, 2]*N[3, 3]

In [3]:
display(gbs.cumulant([1,1,1]))
display(old.cumulant([1,1,1], displacement=False))

A[1, 2]*A[3, 4]*A[5, 6] + A[1, 2]*A[3, 5]*A[4, 6] + A[1, 3]*A[2, 4]*A[5, 6] + A[1, 3]*A[2, 6]*A[4, 5] + A[1, 5]*A[2, 3]*A[4, 6] + A[1, 5]*A[2, 6]*A[3, 4] + A[1, 6]*A[2, 3]*A[4, 5] + A[1, 6]*A[2, 4]*A[3, 5]

conjugate(M[1, 2])*conjugate(N[1, 3])*M[2, 3] + conjugate(M[1, 2])*conjugate(N[2, 3])*M[1, 3] + conjugate(M[1, 3])*conjugate(N[1, 2])*M[2, 3] + conjugate(M[1, 3])*M[1, 2]*N[2, 3] + conjugate(M[2, 3])*M[1, 2]*N[1, 3] + conjugate(M[2, 3])*M[1, 3]*N[1, 2] + conjugate(N[1, 2])*conjugate(N[2, 3])*N[1, 3] + conjugate(N[1, 3])*N[1, 2]*N[2, 3]

### A new Montrealer
The following is the building of the new Montrealer function which is more general and is not restricted to squeezed states but is the covariance for a general Matrix A as long as there is no displacement and no repetition.

In [2]:
from gbs_functions import symmetric_A
import numpy as np
from sympy import Matrix
from itertools import product, permutations

Bitstring function

In [74]:
def bitstrings(n):
    for binary in map(''.join, product('01', repeat=n-1)):
        yield '0'+binary

for i in bitstrings(4):
    print(i)

0000
0001
0010
0011
0100
0101
0110
0111


In [13]:
A = symmetric_A(3)
display(Matrix(A))
x = [2,3,4]
for i in permutations(x):
    print(i)

Matrix([
[A[1, 1], A[1, 2], A[1, 3], A[1, 4], A[1, 5], A[1, 6]],
[A[1, 2], A[2, 2], A[2, 3], A[2, 4], A[2, 5], A[2, 6]],
[A[1, 3], A[2, 3], A[3, 3], A[3, 4], A[3, 5], A[3, 6]],
[A[1, 4], A[2, 4], A[3, 4], A[4, 4], A[4, 5], A[4, 6]],
[A[1, 5], A[2, 5], A[3, 5], A[4, 5], A[5, 5], A[5, 6]],
[A[1, 6], A[2, 6], A[3, 6], A[4, 6], A[5, 6], A[6, 6]]])

(2, 3, 4)
(2, 4, 3)
(3, 2, 4)
(3, 4, 2)
(4, 2, 3)
(4, 3, 2)


In [87]:
n=3
mat = np.arange(1,2*n+1).reshape(2,3) #initiate matrice of indices
graph1 = list(range(1,n))+[n+1] #initiate graphs
graph2 = list(range(n+2,2*n+1))+[n]

bi = '011' #test bitstring
print(mat)
print(np.flip(mat[:,1]))

#print(mat[:,1])
new = np.delete(mat,0,1)
#np.insert(new,1, )

print(mat)
buffer = mat[0,1]
mat[0,1] = mat[1,1]
mat[1,1] = buffer
print(mat)

test = np.copy(mat)
test[1,1]= 0 
print(mat)
print(test)

[[1 2 3]
 [4 5 6]]
[5 2]
[[1 2 3]
 [4 5 6]]
[[1 5 3]
 [4 2 6]]
[[1 5 3]
 [4 2 6]]
[[1 5 3]
 [4 0 6]]


In [134]:
m = 4
A = symmetric_A(m)
power = [1,2,3]

def bitstrings(n):
    for binary in map(''.join, product('01', repeat=n-1)):
        yield '0'+binary

def montrealer(A, power):
    equation = 0

    #reshaping matrix A
    m = int(np.shape(A)[0]/2)
    power = power + [m+i for i in power]
    power = [i-1 for i in power]
    A = A[power][:,power]
    
    #making the original 2 rows matrix
    m = int(np.shape(A)[0]/2)
    original = np.arange(1,2*m+1).reshape(2,m)

    #initial graphs
    graph1 = list(range(1,m))+[m+1]
    graph2 = list(range(m+2,2*m+1))+[m]

    #loop over all bistrings and all permutations
    for bit in bitstrings(m):
        for perm in permutations(range(1,m)):
            B =  np.copy(original)

            for i,j in enumerate(bit):
                if int(j):
                    buffer = B[0,i]
                    B[0,i] = B[1,i]
                    B[1,i] = buffer

            B = B[:,[0]+list(perm)] #first column stays in place always

            #dictionary mapping
            dico = {j:i+1 for i,j in enumerate(B.reshape(1,2*m)[0])}
            new_mapping = {dico[i]:dico[j] for i,j in zip(graph1,graph2)}

            term = 1
            for i,j in dico.items():
                term *= A[i-1,j-1]

            equation += term

    return equation

display(montrealer(A, power))

A[1, 1]*A[2, 2]*A[3, 3]*A[5, 5]*A[6, 6]*A[7, 7] + A[1, 1]*A[2, 2]*A[3, 7]**2*A[5, 5]*A[6, 6] + A[1, 1]*A[2, 3]**2*A[5, 5]*A[6, 7]**2 + 2*A[1, 1]*A[2, 3]*A[2, 7]*A[3, 6]*A[5, 5]*A[6, 7] + A[1, 1]*A[2, 6]**2*A[3, 3]*A[5, 5]*A[7, 7] + A[1, 1]*A[2, 6]**2*A[3, 7]**2*A[5, 5] + A[1, 1]*A[2, 7]**2*A[3, 6]**2*A[5, 5]